apiVersion: skaffold/v2beta7
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: secouriste/data
      context: ../
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/*.ts'
            dest: .